  CREATE TABLE "MI181_RMBANAWA"."CLIENT" 
   (	"CLIENT_ID" NUMBER NOT NULL ENABLE, 
	"CLIENT_FNAME" VARCHAR2(100), 
	"CLIENT_LNAME" VARCHAR2(100), 
	"CLIENT_ADDRESS" VARCHAR2(100), 
	"CLIENT_EMAIL" VARCHAR2(100), 
	 CONSTRAINT "CLIENT_PK" PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_PURCHASE_ORDER" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "MI181_RMBANAWA"."PURCHASE_ORDER" ("PURCHASE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;